modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
authors = "Aaur1s"
description = '''
Cool mod made by Aaur1s!
'''
#logoFile = ""

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"
